import type { FileCategory } from '@/types';

export const CATEGORIES: FileCategory[] = [
  'images',
  'videos',
  'documents',
  'archives',
  'installers',
  'applications',
  'audio',
  'code',
  'other',
];

export const CATEGORY_LABELS: Record<FileCategory, string> = {
  images: 'Images',
  videos: 'Videos',
  documents: 'Documents',
  archives: 'Archives',
  installers: 'Installers',
  applications: 'Applications',
  audio: 'Audio',
  code: 'Code',
  other: 'Other',
};

export const CATEGORY_COLORS: Record<FileCategory, string> = {
  images: '#3b82f6',
  videos: '#ef4444',
  documents: '#f59e0b',
  archives: '#8b5cf6',
  installers: '#ec4899',
  applications: '#06b6d4',
  audio: '#10b981',
  code: '#6366f1',
  other: '#6b7280',
};

const EXTENSION_MAP: Record<string, FileCategory> = {
  jpg: 'images',
  jpeg: 'images',
  png: 'images',
  gif: 'images',
  webp: 'images',
  svg: 'images',
  bmp: 'images',
  ico: 'images',
  heic: 'images',
  raw: 'images',

  mp4: 'videos',
  mkv: 'videos',
  mov: 'videos',
  avi: 'videos',
  wmv: 'videos',
  flv: 'videos',
  webm: 'videos',
  m4v: 'videos',

  pdf: 'documents',
  doc: 'documents',
  docx: 'documents',
  xls: 'documents',
  xlsx: 'documents',
  ppt: 'documents',
  pptx: 'documents',
  txt: 'documents',
  rtf: 'documents',
  odt: 'documents',
  csv: 'documents',
  md: 'documents',

  zip: 'archives',
  rar: 'archives',
  '7z': 'archives',
  tar: 'archives',
  gz: 'archives',
  bz2: 'archives',
  xz: 'archives',

  dmg: 'installers',
  exe: 'installers',
  msi: 'installers',
  pkg: 'installers',
  deb: 'installers',
  rpm: 'installers',
  appimage: 'installers',

  app: 'applications',

  mp3: 'audio',
  wav: 'audio',
  flac: 'audio',
  aac: 'audio',
  ogg: 'audio',
  wma: 'audio',
  m4a: 'audio',

  js: 'code',
  ts: 'code',
  tsx: 'code',
  jsx: 'code',
  py: 'code',
  java: 'code',
  cpp: 'code',
  c: 'code',
  h: 'code',
  hpp: 'code',
  rs: 'code',
  go: 'code',
  rb: 'code',
  php: 'code',
  swift: 'code',
  kt: 'code',
  scala: 'code',
  sh: 'code',
  bash: 'code',
  zsh: 'code',
  yml: 'code',
  yaml: 'code',
  json: 'code',
  xml: 'code',
  html: 'code',
  css: 'code',
  scss: 'code',
  sql: 'code',
  toml: 'code',
  cfg: 'code',
};

export function categoryFromExtension(extension: string): FileCategory {
  const ext = extension.toLowerCase().replace(/^\./, '');
  return EXTENSION_MAP[ext] ?? 'other';
}
